// Album-art colour theming, ported from the Android app's `ui/theme/ColorRoles.kt` (seed extraction and scheme
// generation) and `data/preferences/AlbumArtPaletteStyle.kt` / `AlbumArtColorAccuracy.kt`. The colour science
// underneath (CAM16/HCT, tonal palettes, the Celebi quantizer and the dynamic-colour role rules) is a Swift port of
// Google's Apache-2.0 colour utilities that Android ships inside `com.google.android.material:material` 1.14.0
// (`color/utilities`); see THIRD_PARTY_NOTICES.md. Golden vectors from the real Android classes live in
// Tests/PixlLibraryTests/Fixtures/theme-golden.jsonl (generated by tools/android-reference/ThemeGen.java).
//
// Everything here is pure value maths: no CoreGraphics. The app decodes a ≤128 px thumbnail with ImageIO and passes
// its pixels as ARGB (Android's `Bitmap.getPixels` layout).

import Foundation

/// The palette style setting (Android `AlbumArtPaletteStyle`, stored under `album_art_palette_style_v1`).
public enum ArtworkPaletteStyle: String, Sendable, Hashable, Codable, CaseIterable {
    case tonalSpot = "tonal_spot"
    case vibrant = "vibrant"
    case expressive = "expressive"
    case fruitSalad = "fruit_salad"

    /// Android `AlbumArtPaletteStyle.default`.
    public static let `default`: ArtworkPaletteStyle = .tonalSpot

    /// Persisted value (Android `storageKey`).
    public var storageKey: String { rawValue }

    /// Android `label`.
    public var label: String {
        switch self {
        case .tonalSpot: "Tonal Spot"
        case .vibrant: "Vibrant"
        case .expressive: "Expressive"
        case .fruitSalad: "Fruit Salad"
        }
    }

    /// Android `fromStorageKey`: unknown or missing values fall back to the default.
    public static func fromStorageKey(_ value: String?) -> ArtworkPaletteStyle {
        guard let value, let style = ArtworkPaletteStyle(rawValue: value) else { return .default }
        return style
    }
}

/// The colour-accuracy setting (Android `AlbumArtColorAccuracy`, stored under `album_art_color_accuracy_v1`).
public enum ArtworkColorAccuracy {
    public static let min = 0
    public static let max = 10
    public static let `default` = min
    public static let steps = max - min - 1

    public static func clamp(_ value: Int) -> Int { Swift.min(Swift.max(value, min), max) }
}

/// Every colour role of one scheme, as opaque ARGB (`0xAARRGGBB`), in the order Android stores them
/// (`StoredColorSchemeValues` / Compose `ColorScheme`).
public struct ColorRoles: Sendable, Hashable, Codable {
    public var primary: UInt32
    public var onPrimary: UInt32
    public var primaryContainer: UInt32
    public var onPrimaryContainer: UInt32
    public var inversePrimary: UInt32
    public var secondary: UInt32
    public var onSecondary: UInt32
    public var secondaryContainer: UInt32
    public var onSecondaryContainer: UInt32
    public var tertiary: UInt32
    public var onTertiary: UInt32
    public var tertiaryContainer: UInt32
    public var onTertiaryContainer: UInt32
    public var background: UInt32
    public var onBackground: UInt32
    public var surface: UInt32
    public var onSurface: UInt32
    public var surfaceVariant: UInt32
    public var onSurfaceVariant: UInt32
    public var surfaceTint: UInt32
    public var inverseSurface: UInt32
    public var inverseOnSurface: UInt32
    public var error: UInt32
    public var onError: UInt32
    public var errorContainer: UInt32
    public var onErrorContainer: UInt32
    public var outline: UInt32
    public var outlineVariant: UInt32
    public var scrim: UInt32
    public var surfaceBright: UInt32
    public var surfaceDim: UInt32
    public var surfaceContainer: UInt32
    public var surfaceContainerHigh: UInt32
    public var surfaceContainerHighest: UInt32
    public var surfaceContainerLow: UInt32
    public var surfaceContainerLowest: UInt32
    public var primaryFixed: UInt32
    public var primaryFixedDim: UInt32
    public var onPrimaryFixed: UInt32
    public var onPrimaryFixedVariant: UInt32
    public var secondaryFixed: UInt32
    public var secondaryFixedDim: UInt32
    public var onSecondaryFixed: UInt32
    public var onSecondaryFixedVariant: UInt32
    public var tertiaryFixed: UInt32
    public var tertiaryFixedDim: UInt32
    public var onTertiaryFixed: UInt32
    public var onTertiaryFixedVariant: UInt32

    /// The role names in storage order (also the golden-vector column order).
    public static let roleNames: [String] = [
        "primary", "onPrimary", "primaryContainer", "onPrimaryContainer", "inversePrimary",
        "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
        "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
        "background", "onBackground", "surface", "onSurface", "surfaceVariant", "onSurfaceVariant",
        "surfaceTint", "inverseSurface", "inverseOnSurface", "error", "onError", "errorContainer", "onErrorContainer",
        "outline", "outlineVariant", "scrim", "surfaceBright", "surfaceDim", "surfaceContainer",
        "surfaceContainerHigh", "surfaceContainerHighest", "surfaceContainerLow", "surfaceContainerLowest",
        "primaryFixed", "primaryFixedDim", "onPrimaryFixed", "onPrimaryFixedVariant",
        "secondaryFixed", "secondaryFixedDim", "onSecondaryFixed", "onSecondaryFixedVariant",
        "tertiaryFixed", "tertiaryFixedDim", "onTertiaryFixed", "onTertiaryFixedVariant",
    ]

    /// All roles in `roleNames` order.
    public var values: [UInt32] {
        [primary, onPrimary, primaryContainer, onPrimaryContainer, inversePrimary,
         secondary, onSecondary, secondaryContainer, onSecondaryContainer,
         tertiary, onTertiary, tertiaryContainer, onTertiaryContainer,
         background, onBackground, surface, onSurface, surfaceVariant, onSurfaceVariant,
         surfaceTint, inverseSurface, inverseOnSurface, error, onError, errorContainer, onErrorContainer,
         outline, outlineVariant, scrim, surfaceBright, surfaceDim, surfaceContainer,
         surfaceContainerHigh, surfaceContainerHighest, surfaceContainerLow, surfaceContainerLowest,
         primaryFixed, primaryFixedDim, onPrimaryFixed, onPrimaryFixedVariant,
         secondaryFixed, secondaryFixedDim, onSecondaryFixed, onSecondaryFixedVariant,
         tertiaryFixed, tertiaryFixedDim, onTertiaryFixed, onTertiaryFixedVariant]
    }

    /// Builds roles from `roleNames`-ordered values (48 entries). Nil on a wrong count.
    public init?(values: [UInt32]) {
        guard values.count == ColorRoles.roleNames.count else { return nil }
        var i = 0
        func next() -> UInt32 { defer { i += 1 }; return values[i] }
        primary = next(); onPrimary = next(); primaryContainer = next(); onPrimaryContainer = next()
        inversePrimary = next()
        secondary = next(); onSecondary = next(); secondaryContainer = next(); onSecondaryContainer = next()
        tertiary = next(); onTertiary = next(); tertiaryContainer = next(); onTertiaryContainer = next()
        background = next(); onBackground = next(); surface = next(); onSurface = next()
        surfaceVariant = next(); onSurfaceVariant = next()
        surfaceTint = next(); inverseSurface = next(); inverseOnSurface = next()
        error = next(); onError = next(); errorContainer = next(); onErrorContainer = next()
        outline = next(); outlineVariant = next(); scrim = next(); surfaceBright = next(); surfaceDim = next()
        surfaceContainer = next(); surfaceContainerHigh = next(); surfaceContainerHighest = next()
        surfaceContainerLow = next(); surfaceContainerLowest = next()
        primaryFixed = next(); primaryFixedDim = next(); onPrimaryFixed = next(); onPrimaryFixedVariant = next()
        secondaryFixed = next(); secondaryFixedDim = next(); onSecondaryFixed = next(); onSecondaryFixedVariant = next()
        tertiaryFixed = next(); tertiaryFixedDim = next(); onTertiaryFixed = next(); onTertiaryFixedVariant = next()
    }

    /// Applies `transform` to every role.
    public func map(_ transform: (UInt32) -> UInt32) -> ColorRoles {
        ColorRoles(values: values.map(transform))!
    }
}

/// A light and a dark scheme derived from one seed (Android `ColorSchemePair`).
public struct ColorRolesPair: Sendable, Hashable, Codable {
    public var light: ColorRoles
    public var dark: ColorRoles

    public init(light: ColorRoles, dark: ColorRoles) {
        self.light = light
        self.dark = dark
    }

    public func roles(dark isDark: Bool) -> ColorRoles { isDark ? dark : light }
}

/// Seed extraction and scheme generation (Android `extractSeedColor` / `generateColorSchemeFromSeed`).
public enum ArtworkTheme {
    /// Android's `ColorExtractionConfig.downscaleMaxDimension`: decode artwork at most this many pixels per side.
    public static let extractionMaxDimension = 128

    /// Android `ColorSchemeProcessor.CACHE_ALGORITHM_VERSION`: part of every cache key.
    public static let cacheAlgorithmVersion = "algo_v7"

    /// The scheme cache key suffix Android stores in `album_art_themes.paletteStyle`
    /// (`<style>|accuracy_<n>|algo_v7`).
    public static func paletteCacheKey(style: ArtworkPaletteStyle, accuracyLevel: Int) -> String {
        "\(style.storageKey)|accuracy_\(ArtworkColorAccuracy.clamp(accuracyLevel))|\(cacheAlgorithmVersion)"
    }

    /// The seed colour of an image given as ARGB pixels (`Bitmap.getPixels` layout, non-premultiplied), already
    /// downscaled to at most `extractionMaxDimension` per side. Android `selectSeedColorArgbFromPixels`.
    public static func seedColor(argbPixels: [UInt32], accuracyLevel: Int = ArtworkColorAccuracy.default) -> UInt32 {
        SeedColorSelector.select(pixels: argbPixels, accuracyLevel: accuracyLevel)
    }

    /// Convenience for RGBA8 buffers (row-major, `bytesPerRow` ≥ 4·width). Premultiplied pixels are
    /// un-premultiplied first, so the result matches a non-premultiplied Android bitmap.
    public static func seedColor(rgba: [UInt8], width: Int, height: Int, bytesPerRow: Int? = nil,
                                 premultipliedAlpha: Bool = true,
                                 accuracyLevel: Int = ArtworkColorAccuracy.default) -> UInt32 {
        seedColor(argbPixels: argbPixels(rgba: rgba, width: width, height: height, bytesPerRow: bytesPerRow,
                                         premultipliedAlpha: premultipliedAlpha),
                  accuracyLevel: accuracyLevel)
    }

    /// Converts an RGBA8 buffer to ARGB pixels.
    public static func argbPixels(rgba: [UInt8], width: Int, height: Int, bytesPerRow: Int? = nil,
                                  premultipliedAlpha: Bool = true) -> [UInt32] {
        let stride = bytesPerRow ?? width * 4
        guard width > 0, height > 0, stride >= width * 4, rgba.count >= stride * (height - 1) + width * 4 else {
            return []
        }
        var out = [UInt32]()
        out.reserveCapacity(width * height)
        for y in 0..<height {
            var o = y * stride
            for _ in 0..<width {
                var r = UInt32(rgba[o]), g = UInt32(rgba[o + 1]), b = UInt32(rgba[o + 2])
                let a = UInt32(rgba[o + 3])
                if premultipliedAlpha, a > 0, a < 255 {
                    r = min(255, (r * 255 + a / 2) / a)
                    g = min(255, (g * 255 + a / 2) / a)
                    b = min(255, (b * 255 + a / 2) / a)
                }
                out.append(a << 24 | r << 16 | g << 8 | b)
                o += 4
            }
        }
        return out
    }

    /// Light and dark schemes for a seed (Android `generateColorSchemeFromSeed`): near-grey seeds give grey
    /// schemes; anything that fails falls back to `ArtworkTheme.fallbackPair`.
    public static func schemePair(seed: UInt32, style: ArtworkPaletteStyle = .default) -> ColorRolesPair {
        SchemeBuilder.pair(seed: seed, style: style)
    }

    /// Android `generateMonochromeColorSchemeFromSeed`.
    public static func monochromePair(seed: UInt32) -> ColorRolesPair {
        SchemeBuilder.monochromePair(seed: seed)
    }

    /// The seed of PixlAudio's own palette (Android `LightPrimary`, `0xFF6C4FF5`). iOS has no wallpaper colours, so
    /// the app chrome is themed from this seed where Android would use the system's dynamic scheme.
    public static let brandSeed: UInt32 = 0xFF6C_4FF5

    /// The tonal-spot pair of `brandSeed`.
    public static let brandPair: ColorRolesPair = schemePair(seed: brandSeed)

    /// The app-wide accent scheme of a picked colour (iOS-only, owner request 2026-10-07: Settings › Appearance ›
    /// Accent Color). TonalSpot surfaces and role tones with the primary at the seed's own chroma (at least 36), so a
    /// vivid pick stays vivid in light mode and every role keeps its contrast. Near-grey seeds give grey schemes.
    /// The default accent is `brandPair`, not `accentPair(seed: brandSeed)`, so nothing changes until a colour is
    /// picked.
    public static func accentPair(seed: UInt32) -> ColorRolesPair {
        SchemeBuilder.accentPair(seed: seed)
    }
}
