import SwiftUI

// The PixlAudio logo (concept C, "Glyph"). Both images are generated by `ci/make-icon.py` from the app icon's
// geometry; regenerate them there, never edit them by hand. They are logo artwork (like `WelcomeArt`), not glass:
// never use them as a container background, and never put `glassEffect` on them inside a glass card.

/// The full-colour logo: the app-icon tile with continuous corners and transparent outside, light and dark from the
/// `BrandMark` image set. Rendered at 120 pt (it is also the launch-screen image), so it is sharp up to that size.
struct BrandMark: View {
    var body: some View {
        Image("BrandMark")
            .resizable()
            .interpolation(.high)
            .aspectRatio(1, contentMode: .fit)
            .accessibilityHidden(true)
    }
}

/// The one-colour logo glyph (Android `pixelplay_base_monochrome`): a template vector that takes the foreground
/// style, e.g. `BrandGlyph().foregroundStyle(theme.onPrimaryContainer)`, so it follows the palette. Its square box has
/// the Android drawable's margins (the glyph fills 88.5 % of the height), so Android's sizes port 1:1.
struct BrandGlyph: View {
    var body: some View {
        Image("BrandGlyph")
            .renderingMode(.template)
            .resizable()
            .aspectRatio(1, contentMode: .fit)
            .accessibilityHidden(true)
    }
}
