"""Regenerate requirements.lock and requirements-test.lock (needs `uv` on PATH, or --uv <path>).

    python ci/lock.py            # from cloud/runpod-worker/

requirements.lock: requirements.in resolved for the base image (CPython 3.12, x86_64 manylinux_2_39 = Ubuntu
24.04) under constraints.txt, with --generate-hashes; then the packages the base image provides (torch,
torchaudio, torchvision, triton, nvidia-*, cuda-*) are removed, and qwen-asr is appended without its
dependencies (see requirements.in). The Dockerfile installs the result with `pip install --no-deps
--require-hashes`, so every installed file is pinned by hash and nothing touches torch.

requirements-test.lock: requirements-test.in for the CPU-only test stage (python:3.12-slim).
Stdlib only.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLATFORM = "x86_64-manylinux_2_39"
PYTHON = "3.12"
FROM_BASE = re.compile(r"^(torch|torchaudio|torchvision|triton|nvidia-[a-z0-9-]+|cuda-[a-z0-9-]+)==", re.I)
NO_DEPS = ["qwen-asr==0.0.6"]


def compile_(uv: str, src: str, out: Path, *extra: str) -> str:
    """uv pip compile, run from ROOT with ROOT-relative inputs (uv splits some absolute paths at spaces)."""
    args = [uv, "pip", "compile", src, "--generate-hashes", "--python-version", PYTHON,
            "--python-platform", PLATFORM, "--no-header", "--no-annotate", "--quiet", "-o", str(out), *extra]
    subprocess.run(args, check=True, cwd=ROOT)
    return out.read_text(encoding="utf-8")


def drop_base_packages(text: str) -> tuple[str, list[str]]:
    """Remove each `name==ver \\` block (its hash continuation lines included) whose name the base provides."""
    kept, dropped, skipping = [], [], False
    for line in text.splitlines():
        if line and not line[0].isspace():
            skipping = bool(FROM_BASE.match(line))
            if skipping:
                dropped.append(line.split(" ", 1)[0])
        if not skipping:
            kept.append(line)
    return "\n".join(kept).rstrip() + "\n", dropped


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--uv", default=shutil.which("uv") or "uv")
    args = parser.parse_args(argv)
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        main_lock = compile_(args.uv, "requirements.in", tmp_path / "main.txt", "-c", "constraints.txt")
        main_lock, dropped = drop_base_packages(main_lock)
        nodeps_in = tmp_path / "nodeps.in"
        nodeps_in.write_text("\n".join(NO_DEPS) + "\n", encoding="utf-8")
        nodeps = compile_(args.uv, str(nodeps_in), tmp_path / "nodeps.txt", "--no-deps")
        header = (
            "# GENERATED by ci/lock.py from requirements.in + constraints.txt. Do not edit by hand.\n"
            f"# Target: CPython {PYTHON}, {PLATFORM} (the pytorch/pytorch base image, Ubuntu 24.04).\n"
            f"# Provided by the base image, so left out: {', '.join(sorted(set(n.split('==')[0] for n in dropped)))}.\n"
            "# Installed with: pip install --no-deps --require-hashes -r requirements.lock\n"
        )
        tail = "\n# Installed without its dependencies (see requirements.in):\n" + nodeps
        (ROOT / "requirements.lock").write_text(header + main_lock + tail, encoding="utf-8", newline="\n")

        test_lock = compile_(args.uv, "requirements-test.in", tmp_path / "test.txt")
        (ROOT / "requirements-test.lock").write_text(
            "# GENERATED by ci/lock.py from requirements-test.in. Do not edit by hand.\n" + test_lock,
            encoding="utf-8", newline="\n")
    print(f"requirements.lock: dropped {len(dropped)} base packages; requirements-test.lock written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
