import androidx.media3.common.audio.AudioProcessor;
import com.theveloper.pixelplay.data.media.ReplayGainManager;
import com.theveloper.pixelplay.data.model.Curve;
import com.theveloper.pixelplay.data.service.player.DualPlayerEngineKt;
import com.theveloper.pixelplay.data.service.player.MidSideVocalProcessor;
import com.theveloper.pixelplay.data.tais.dsp.Fft;
import com.theveloper.pixelplay.data.tais.lyrics.CtcAlignmentCore;
import com.theveloper.pixelplay.utils.EnvelopeKt;
import java.io.PrintStream;
import java.lang.reflect.Method;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.List;
import java.util.Locale;

/**
 * Golden vectors for PixlAudioCore (stage 3b). Runs the Android app's compiled classes on a desktop JVM and writes
 * Packages/PixlCore/Tests/PixlAudioCoreTests/Fixtures/audio-android-golden.txt (format in the file header and in
 * tools/android-reference/README.md).
 *
 * What runs for real: utils/Envelope.kt `envelope`, ReplayGainManager (`gainDbToVolume`, `getVolumeMultiplier`, the
 * private `parseGainString` through reflection), DualPlayerEngine.kt `shouldResumeAfterTransientAudioFocusLoss`,
 * data/tais/dsp/Fft.kt (`Fft.transform`, `Fft.Workspace`), data/tais/lyrics/CtcAlignmentCore.kt and
 * MidSideVocalProcessor (fed through Media3's AudioProcessor interface). The crossfade lines ("C") re-evaluate the
 * gain expression of DualPlayerEngine.performOverlapTransition with the real `envelope` (that loop is not callable
 * on its own).
 *
 * Classpath (Windows separators): the app's compileDebugKotlin/classes, kotlin-stdlib 2.4.0, media3-common 1.10.1
 * classes.jar (from the .aar), taglib 1.0.6 classes.jar (ReplayGainManager links against it), guava 33.3.1-android,
 * annotation-jvm 1.10.0, android.jar (platforms/android-37.0).
 *   javac -cp "$CP" AudioGen.java && java -Duser.language=en -Duser.country=US -cp "$CP;." AudioGen <repo root>
 * Generated with JDK 26.
 */
public class AudioGen {
    static final StringBuilder out = new StringBuilder();
    static long seed = 0x5EED_A0D1_0C0E_3B00L;

    static long next() {
        seed += 0x9E3779B97F4A7C15L;
        long z = seed;
        z = (z ^ (z >>> 30)) * 0xBF58476D1CE4E5B9L;
        z = (z ^ (z >>> 27)) * 0x94D049BB133111EBL;
        return z ^ (z >>> 31);
    }

    static int nextInt(int bound) { return (int) Long.remainderUnsigned(next(), bound); }

    /** Uniform in [-1, 1), exactly representable (24-bit grid). */
    static float unit() { return (float) (next() >>> 40) / 8388608f - 1f; }

    static String f(float v) { return String.format("0x%08x", Float.floatToRawIntBits(v)); }

    static void line(String s) { out.append(s).append('\n'); }

    public static void main(String[] args) throws Exception {
        Locale.setDefault(Locale.US);
        Path root = Path.of(args[0]);
        Path file = root.resolve("Packages/PixlCore/Tests/PixlAudioCoreTests/Fixtures/audio-android-golden.txt");
        line("// Generated by tools/android-reference/AudioGen.java from the compiled Android classes. Do not edit.");
        line("// Floats are IEEE-754 bit patterns. E curve p result | C durationMs elapsedMs curveIn curveOut startVolume target in out");
        line("// G gainDb preAmpDb volume | M track|- album|- useAlbum preAmp volume | P utf8hex result|null | R m mp t ap ai result");
        line("// T size inverse re... im... -> re... im... (Fft.transform) | W samples first,end,inStart,inEnd;... | V scores... result");
        line("// A blank frames vocab length logProbs(frames*vocab)... extended... -> path...|null|THROW");
        line("// S float|s16 attenuation frames input... -> output...");
        envelopes();
        crossfades();
        replayGain();
        focus();
        fft();
        ctc();
        midSide();
        Files.createDirectories(file.getParent());
        Files.writeString(file, out.toString(), StandardCharsets.UTF_8);
        System.err.println("wrote " + file + " (" + out.length() + " chars)");
    }

    // ------------------------------------------------------------------ transitions

    static final Curve[] CURVES = {Curve.LINEAR, Curve.EXP, Curve.LOG, Curve.S_CURVE};

    static void envelopes() {
        List<Float> ps = new ArrayList<>();
        float[] special = {-1f, -0f, 0f, Float.MIN_VALUE, 1e-30f, 1e-7f, 0.001f, 0.25f, 0.5f, 0.75f, 0.999f,
            Math.nextDown(1f), 1f, Math.nextUp(1f), 1.5f, 1e30f, Float.POSITIVE_INFINITY, Float.NEGATIVE_INFINITY, Float.NaN};
        for (float s : special) ps.add(s);
        for (int i = 0; i <= 1000; i++) ps.add(i / 1000f);
        for (int i = 0; i < 300; i++) ps.add((unit() + 1f) / 2f);
        for (Curve c : CURVES) for (float p : ps) line("E " + c.name() + " " + f(p) + " " + f(EnvelopeKt.envelope(p, c)));
    }

    static void crossfades() {
        long[] durations = {0, 1, 499, 500, 501, 2000, 3333, 12000};
        float[] starts = {1f, 0.8f, 0.37f, 0f, 1.2f};
        Float[] targets = {null, 1f, 0.5f, 1.4f, 0f};
        for (long setting : durations) {
            long duration = Math.max(setting, 500L);
            for (Curve in : CURVES) for (Curve outC : CURVES) {
                float start = starts[nextInt(starts.length)];
                Float target = targets[nextInt(targets.length)];
                for (int k = 0; k < 12; k++) {
                    long elapsedRaw = k == 0 ? 0 : k == 11 ? duration + 50 : (long) nextInt((int) duration + 1);
                    long elapsed = Math.min(elapsedRaw, duration);
                    float progress = Math.max(0f, Math.min(1f, (float) elapsed / (float) duration));
                    float volIn = EnvelopeKt.envelope(progress, in);
                    float volOut = 1f - EnvelopeKt.envelope(progress, outC);
                    float t = target == null ? 1f : target;
                    float gIn = Math.max(0f, Math.min(1f, volIn * t));
                    // performOverlapTransition: outgoingStartVolume = playerA.volume.coerceIn(0f, 1f)
                    float outgoingStart = Math.max(0f, Math.min(1f, start));
                    float gOut = Math.max(0f, Math.min(1f, volOut * outgoingStart));
                    line("C " + setting + " " + elapsedRaw + " " + in.name() + " " + outC.name() + " " + f(start) + " "
                        + (target == null ? "-" : f(target)) + " " + f(gIn) + " " + f(gOut));
                }
            }
        }
    }

    // ------------------------------------------------------------------ ReplayGain

    static void replayGain() throws Exception {
        ReplayGainManager m = new ReplayGainManager();
        float[] pre = {0f, -6f, 3.5f, 12f};
        List<Float> gains = new ArrayList<>();
        for (float g = -60f; g <= 30f; g += 0.37f) gains.add(g);
        float[] special = {0f, -0f, 6.0206f, 6.0207f, -6.54f, 3.21f, 1e30f, -1e30f, Float.MIN_VALUE,
            Float.POSITIVE_INFINITY, Float.NEGATIVE_INFINITY, Float.NaN};
        for (float s : special) gains.add(s);
        for (int i = 0; i < 200; i++) gains.add(unit() * 40f);
        for (float g : gains) for (float p : pre) line("G " + f(g) + " " + f(p) + " " + f(m.gainDbToVolume(g, p)));

        Float[] opts = {null, -6.54f, 3.21f, -12f, 0f, 9f, Float.NaN};
        for (Float t : opts) for (Float a : opts) for (boolean album : new boolean[]{false, true}) for (float p : pre) {
            ReplayGainManager.ReplayGainValues v = new ReplayGainManager.ReplayGainValues(t, a);
            line("M " + (t == null ? "-" : f(t)) + " " + (a == null ? "-" : f(a)) + " " + album + " " + f(p) + " "
                + f(m.getVolumeMultiplier(v, album, p)));
        }
        line("M null false " + f(0f) + " " + f(m.getVolumeMultiplier(null, false, 0f)));

        Method parse = ReplayGainManager.class.getDeclaredMethod("parseGainString", String.class);
        parse.setAccessible(true);
        String[] inputs = {"-6.54 dB", "+3.21 dB", "-6.54dB", "  -6.54  DB ", "-6.54 db", "-6.54 Db", "1e3", "0x1p3",
            "NaN", "Infinity", "-Infinity", "+Infinity dB", "abc", "", " ", "dB", "-6.54 dB dB", "-6,54 dB", "1.5f",
            "1.5d", "1.5F dB", "1.5D", ".5", "5.", ".", "-.5e-2", "1e", "1e+", "\t-3.0\n", " -3.0", " -3",
            "　-3　", "-3 d B", "−3", "3.4028236E38", "3.4028235E38", "1e-50", "1.17549435E-38",
            "1.4E-45", "7.0E-46", "１２", "0x1.8p1", "0X1P-2f", "0x.8p0", "0x1", "0x1p", "+-1", "--1",
            "1 2", "1_000", "١٢٣", "dbdb5", "5dbx", "-0", "-0.0 dB", "000123.4500", "1e39", "-1e39",
            "123456789012345678901234567890", "0.000000000000000000000000000000000000000000001", "4.9E-324",
            "\u0000 1", "1\u0000", "\u001f-2.5 ", "\u0085-1", " -1", "-6.54 dBFS", "-6.54 LU",
            "-6.540000000000000000000000001 dB", "16777217", "0.1", "0.2", "0.30000001192092896", "1.00000005960464477539",
            "1.0000000596046448", "+", "-", "e5", "Infinityf", "NaNd", "nan", "infinity", "1.e5", "1.E-5d", "0x1.fffffep127",
            "0x1.fffffffp127", "0x0.000002p-126", "\t\r\n", "\u000b5\u000c", "D", "B", "dbB", "d-6.54b", "-6.54 dBd"};
        HexFormat hex = HexFormat.of();
        for (String s : inputs) {
            Object r = parse.invoke(m, s);
            line("P " + (s.isEmpty() ? "-" : hex.formatHex(s.getBytes(StandardCharsets.UTF_8))) + " "
                + (r == null ? "null" : f((Float) r)));
        }
    }

    static void focus() {
        for (int bits = 0; bits < 32; bits++) {
            boolean a = (bits & 1) != 0, b = (bits & 2) != 0, c = (bits & 4) != 0, d = (bits & 8) != 0, e = (bits & 16) != 0;
            line("R " + a + " " + b + " " + c + " " + d + " " + e + " "
                + DualPlayerEngineKt.shouldResumeAfterTransientAudioFocusLoss(a, b, c, d, e));
        }
    }

    // ------------------------------------------------------------------ FFT

    static void fft() {
        int[] sizes = {1, 2, 3, 4, 5, 6, 7, 8, 15, 16, 31, 64, 93, 100, 128, 186, 255, 256, 6144};
        for (int n : sizes) {
            for (boolean inverse : new boolean[]{false, true}) {
                float[] re = new float[n], im = new float[n];
                for (int i = 0; i < n; i++) { re[i] = unit(); im[i] = unit(); }
                StringBuilder sb = new StringBuilder("T " + n + " " + inverse);
                for (float v : re) sb.append(' ').append(f(v));
                for (float v : im) sb.append(' ').append(f(v));
                float[] wr = re.clone(), wi = im.clone();
                Fft.INSTANCE.transform(re, im, inverse);
                new Fft.Workspace(n).transform(wr, wi, inverse);
                for (int i = 0; i < n; i++) {
                    if (Float.floatToRawIntBits(wr[i]) != Float.floatToRawIntBits(re[i])
                        || Float.floatToRawIntBits(wi[i]) != Float.floatToRawIntBits(im[i]))
                        throw new IllegalStateException("workspace mismatch at " + n);
                }
                sb.append(" ->");
                for (float v : re) sb.append(' ').append(f(v));
                for (float v : im) sb.append(' ').append(f(v));
                line(sb.toString());
            }
        }
    }

    // ------------------------------------------------------------------ CTC

    static void ctc() {
        int[] counts = {0, 1, 399, 400, 401, 719, 720, 721, 1040, 256000, 256001, 256399, 256400, 256720, 320000,
            320400, 2858256, 5_000_000};
        for (int s : counts) windows(s);
        for (int i = 0; i < 40; i++) windows(nextInt(3_000_000));

        CtcAlignmentCore core = CtcAlignmentCore.INSTANCE;
        for (int c = 0; c < 400; c++) {
            int vocab = 2 + nextInt(5);
            int blank = nextInt(8) == 0 ? 1 + nextInt(vocab - 1) : 0;
            int[] extended;
            int kind = nextInt(10);
            if (kind < 7) {
                int tokens = nextInt(7);
                extended = new int[2 * tokens + 1];
                for (int t = 0; t < tokens; t++) {
                    int label;
                    do { label = nextInt(vocab); } while (label == blank);
                    extended[2 * t] = blank;
                    extended[2 * t + 1] = label;
                }
                extended[2 * tokens] = blank;
                if (nextInt(6) == 0 && extended.length > 2) extended = java.util.Arrays.copyOf(extended, extended.length - 1);
            } else {
                extended = new int[1 + nextInt(8)];
                for (int t = 0; t < extended.length; t++) extended[t] = nextInt(vocab);
            }
            int frames = c < 8 ? c : 1 + nextInt(40);
            float[][] lp = new float[frames][vocab];
            int style = nextInt(4);
            for (int t = 0; t < frames; t++) for (int v = 0; v < vocab; v++) {
                float x;
                switch (style) {
                    case 0 -> x = -0.25f * nextInt(41);          // many ties
                    case 1 -> x = (unit() - 1f) * 10f;             // general floats
                    case 2 -> x = nextInt(9) == 0 ? Float.NEGATIVE_INFINITY : -0.5f * nextInt(9);
                    default -> x = nextInt(3) == 0 ? -0.01f : -12f; // the Android test's emission style
                }
                lp[t][v] = x;
            }
            StringBuilder sb = new StringBuilder("A " + blank + " " + frames + " " + vocab + " " + extended.length);
            for (float[] row : lp) for (float v : row) sb.append(' ').append(f(v));
            for (int e : extended) sb.append(' ').append(e);
            sb.append(" ->");
            try {
                int[] path = core.align(lp, extended, blank, () -> kotlin.Unit.INSTANCE);
                if (path == null) sb.append(" null");
                else for (int p : path) sb.append(' ').append(p);
            } catch (IllegalArgumentException e) {
                sb.append(" THROW");
            }
            line(sb.toString());
        }
        // The cell limit (64 Mi cells) is checked before allocating.
        line("A 0 10000 2 6710 " + "-> SIZE " + (sizeThrows(10000, 6710) ? "THROW" : "OK"));
        line("A 0 10000 2 6711 " + "-> SIZE " + (sizeThrows(10000, 6711) ? "THROW" : "OK"));

        float[] pool = {0f, -0f, 0.3f, Math.nextDown(0.3f), 0.45f, Math.nextDown(0.45f), 1f, Math.nextUp(1f), -0.1f,
            0.95f, 0.05f, 0.8f, 0.7f, Float.NaN, Float.POSITIVE_INFINITY, 0.5f, 0.6f, 0.2f};
        for (int c = 0; c < 300; c++) {
            int n = nextInt(9);
            List<Float> scores = new ArrayList<>();
            for (int i = 0; i < n; i++) scores.add(nextInt(3) == 0 ? (unit() + 1f) / 2f : pool[nextInt(pool.length)]);
            StringBuilder sb = new StringBuilder("V");
            for (float v : scores) sb.append(' ').append(f(v));
            sb.append(" -> ").append(core.acceptsWordEvidence(scores));
            line(sb.toString());
        }
    }

    static boolean sizeThrows(int frames, int length) {
        // Smallest case that exercises the check without allocating: frames*length vs 64 Mi.
        try {
            float[][] lp = new float[frames][];
            CtcAlignmentCore.INSTANCE.align(lp, new int[length], 0, () -> { throw new IllegalStateException("reached"); });
            return false;
        } catch (IllegalArgumentException e) {
            return true;
        } catch (RuntimeException e) {
            return false; // passed the check (then failed on the null rows), i.e. accepted
        }
    }

    static void windows(int samples) {
        StringBuilder sb = new StringBuilder("W " + samples);
        for (CtcAlignmentCore.Window w : CtcAlignmentCore.INSTANCE.windows(samples)) {
            sb.append(' ').append(w.getFirstFrame()).append(',').append(w.getEndFrame()).append(',')
                .append(w.getInputStartSample()).append(',').append(w.getInputEndSample());
        }
        line(sb.toString());
    }

    // ------------------------------------------------------------------ mid/side

    static void midSide() {
        float[] attenuations = {-0.5f, 0f, 0.25f, 0.5f, 0.75f, 1f, 1.5f, Float.NaN, 0.33f};
        for (float att : attenuations) {
            for (boolean isFloat : new boolean[]{true, false}) {
                int frames = 64;
                MidSideVocalProcessor p = new MidSideVocalProcessor(() -> att);
                p.configure(new AudioProcessor.AudioFormat(44100, 2, isFloat ? 4 : 2));
                ByteBuffer in = ByteBuffer.allocateDirect(frames * 2 * (isFloat ? 4 : 2)).order(ByteOrder.nativeOrder());
                StringBuilder sb = new StringBuilder("S " + (isFloat ? "float" : "s16") + " " + f(att) + " " + frames);
                for (int i = 0; i < frames * 2; i++) {
                    if (isFloat) {
                        float v = i < 4 ? new float[]{1f, -1f, 1.5f, 1.5f}[i] : unit() * 1.5f;
                        in.putFloat(v);
                        sb.append(' ').append(f(v));
                    } else {
                        short v = i < 6 ? new short[]{32767, 32767, -32768, -32768, 32767, -32768}[i] : (short) nextInt(65536);
                        in.putShort(v);
                        sb.append(' ').append(v);
                    }
                }
                in.flip();
                p.queueInput(in);
                ByteBuffer o = p.getOutput().order(ByteOrder.nativeOrder());
                sb.append(" ->");
                while (o.hasRemaining()) {
                    if (isFloat) sb.append(' ').append(f(o.getFloat()));
                    else sb.append(' ').append(o.getShort());
                }
                line(sb.toString());
            }
        }
    }
}
